
import React from 'react';
import { Shield, Zap, Lock, Eye, BarChart3, Download } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

const About = () => {
  const features = [
    {
      icon: Eye,
      title: 'Advanced Threat Detection',
      description: 'Our machine learning algorithms analyze log patterns to identify sophisticated attack vectors including brute-force attempts, port scanning, and denial-of-service attacks.'
    },
    {
      icon: Zap,
      title: 'Real-time Processing',
      description: 'Process large log files efficiently with our optimized parsing engine. Get results in minutes, not hours, even for multi-gigabyte log files.'
    },
    {
      icon: Shield,
      title: 'Intelligence Integration',
      description: 'Cross-reference suspicious IP addresses with public threat intelligence feeds and blacklists to provide comprehensive threat context.'
    },
    {
      icon: BarChart3,
      title: 'Visual Analytics',
      description: 'Transform raw log data into actionable insights with interactive charts, timelines, and geographic visualizations of attack patterns.'
    },
    {
      icon: Download,
      title: 'Comprehensive Reports',
      description: 'Generate detailed incident reports in multiple formats (PDF, CSV) for compliance, documentation, and threat hunting activities.'
    },
    {
      icon: Lock,
      title: 'Privacy & Security',
      description: 'Your log data is processed securely with encryption in transit and at rest. No data retention ensures your sensitive information stays private.'
    }
  ];

  const threatTypes = [
    {
      name: 'Brute-force Attacks',
      description: 'Detects repeated login failures and password spraying attempts across SSH, FTP, and web services.'
    },
    {
      name: 'Port Scanning',
      description: 'Identifies reconnaissance activities and vulnerability scanning from both internal and external sources.'
    },
    {
      name: 'DoS/DDoS Attacks',
      description: 'Recognizes denial-of-service patterns including request flooding and resource exhaustion attempts.'
    },
    {
      name: 'Web Application Attacks',
      description: 'Spots SQL injection, XSS, and other OWASP Top 10 attack patterns in web server logs.'
    },
    {
      name: 'Lateral Movement',
      description: 'Identifies suspicious internal network activity that may indicate compromised systems.'
    },
    {
      name: 'Data Exfiltration',
      description: 'Detects unusual data transfer patterns that could indicate unauthorized data access or theft.'
    }
  ];

  return (
    <div className="min-h-screen py-12 bg-gradient-to-br from-background to-primary/5">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <div className="text-center space-y-6 mb-16">
          <h1 className="text-4xl lg:text-5xl font-bold bg-gradient-to-r from-foreground to-primary bg-clip-text text-transparent">
            About LogShield
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
            LogShield is a cutting-edge cybersecurity platform designed to help security professionals 
            identify and respond to threats through comprehensive log file analysis. Built by security 
            experts for security teams.
          </p>
        </div>

        {/* Mission Statement */}
        <Card className="mb-16 bg-gradient-to-r from-primary/5 to-accent/5 border-primary/20">
          <CardContent className="p-8 lg:p-12">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
              <div>
                <h2 className="text-3xl font-bold mb-4">Our Mission</h2>
                <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                  In today's threat landscape, security teams are overwhelmed by the volume of log data 
                  generated by their infrastructure. LogShield transforms this challenge into an advantage 
                  by providing intelligent, automated analysis that reveals hidden threats and attack patterns.
                </p>
                <p className="text-lg text-muted-foreground leading-relaxed">
                  We believe that every organization deserves enterprise-grade security capabilities, 
                  regardless of size or budget. That's why we've made LogShield accessible, powerful, 
                  and easy to use.
                </p>
              </div>
              <div className="relative">
                <div className="pulse-border border-2 rounded-xl p-6 bg-card/50 backdrop-blur-sm">
                  <div className="text-center">
                    <Shield className="w-16 h-16 text-primary mx-auto mb-4" />
                    <div className="text-2xl font-bold text-primary mb-2">24/7</div>
                    <div className="text-sm text-muted-foreground">Threat Detection</div>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Features Grid */}
        <div className="mb-16">
          <div className="text-center space-y-4 mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold">Platform Capabilities</h2>
            <p className="text-xl text-muted-foreground">
              Comprehensive security analysis powered by advanced algorithms
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="border-border/50 bg-card/50 backdrop-blur-sm hover:bg-card/70 transition-all duration-300 group">
                <CardHeader className="space-y-4">
                  <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                    <feature.icon className="w-6 h-6 text-primary" />
                  </div>
                  <CardTitle className="text-xl">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-base leading-relaxed">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Threat Detection */}
        <div className="mb-16">
          <div className="text-center space-y-4 mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold">Threat Detection Coverage</h2>
            <p className="text-xl text-muted-foreground">
              Comprehensive protection against modern cyber threats
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {threatTypes.map((threat, index) => (
              <Card key={index} className="border-border/50 bg-card/50 backdrop-blur-sm">
                <CardHeader>
                  <CardTitle className="text-lg">{threat.name}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-base">
                    {threat.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Technology Stack */}
        <Card className="bg-gradient-to-r from-secondary/30 to-muted/30">
          <CardHeader className="text-center">
            <CardTitle className="text-3xl">Built for Performance</CardTitle>
            <CardDescription className="text-lg">
              Engineered with modern technologies for speed, reliability, and scale
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
              <div>
                <div className="text-2xl font-bold text-primary mb-2">React</div>
                <div className="text-sm text-muted-foreground">Modern UI Framework</div>
              </div>
              <div>
                <div className="text-2xl font-bold text-primary mb-2">Python</div>
                <div className="text-sm text-muted-foreground">Backend Processing</div>
              </div>
              <div>
                <div className="text-2xl font-bold text-primary mb-2">ML</div>
                <div className="text-sm text-muted-foreground">Threat Intelligence</div>
              </div>
              <div>
                <div className="text-2xl font-bold text-primary mb-2">Cloud</div>
                <div className="text-sm text-muted-foreground">Scalable Infrastructure</div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default About;
