// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siuipynvedyprwlosdxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdWlweW52ZWR5cHJ3bG9zZHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzQ0MjcsImV4cCI6MjA2NzY1MDQyN30.tcGnXhBQzQacm4LaeZ4H77X4-8lMLNly_UueLRh1GXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});